# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0002_participant_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], default=b'female', max_length=16),
        ),
    ]
