# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0003_set_default_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselornote',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
