Feature: Autogenerated Run-Through

Run through the entire intervention. This test is generated from the
content in the database. Hopefully, this will help us keep 
up to date with changing content. To create this, I run a 
pull_from_prod to the test instance, then run a dev server
on port 8001 with the settings_test and do
curl http://localhost:8001/testgen/ > intervention/features/auto_runthrough.feature
Don't edit this feature file directly. Edit templates/intervention/testgen.html instead

    Scenario: Automated Run-Through
      Using selenium
      Given I am logged in as a counselor
      When I access the url "/"
      When I click the "Let's get started!" link
      When I click the "Intervene" link
      When I fill in "test" in the "name" form field
      When I fill in "test" in the "id_number" form field
      When I submit the "login-participant-form" form
      Then I am on the Intervention page


   
      ## SESSION 1

      When I click on Session 1
      When I click on Activity 1
      Then I am on the Activity 1 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 2
      Then I am on the Activity 2 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 3
      Then I am on the Activity 3 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 4
      Then I am on the Activity 4 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 5
      Then I am on the Activity 5 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 6
      Then I am on the Activity 6 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 7
      Then I am on the Activity 7 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 8
      Then I am on the Activity 8 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 9
      Then I am on the Activity 9 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 10
      Then I am on the Activity 10 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 11
      Then I am on the Activity 11 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 12
      Then I am on the Activity 12 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 13
      Then I am on the Activity 13 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 14
      Then I am on the Activity 14 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 15
      Then I am on the Activity 15 page
      When I click on Complete Activity
      When I click on Session 1
      When I click on Activity 16
      Then I am on the Activity 16 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 1
      When I click on Activity 17
      Then I am on the Activity 17 page
      When I click on Complete Activity
      When I click on Session 1
      
   
      ## SESSION 2

      When I click on Session 2
      When I click on Activity 1
      Then I am on the Activity 1 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 2
      Then I am on the Activity 2 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 3
      Then I am on the Activity 3 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 4
      Then I am on the Activity 4 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 5
      Then I am on the Activity 5 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 6
      Then I am on the Activity 6 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 7
      Then I am on the Activity 7 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 8
      Then I am on the Activity 8 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 9
      Then I am on the Activity 9 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 10
      Then I am on the Activity 10 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 11
      Then I am on the Activity 11 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 12
      Then I am on the Activity 12 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 2
      When I click on Activity 13
      Then I am on the Activity 13 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 2
      When I click on Activity 14
      Then I am on the Activity 14 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 2
      When I click on Activity 15
      Then I am on the Activity 15 page
      When I click on Complete Activity
      When I click on Session 2
      When I click on Activity 16
      Then I am on the Activity 16 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 2
      When I click on Activity 17
      Then I am on the Activity 17 page
      When I click on Complete Activity
      When I click on Session 2
      
   
      ## SESSION 3

      When I click on Session 3
      When I click on Activity 1
      Then I am on the Activity 1 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 2
      Then I am on the Activity 2 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 3
      Then I am on the Activity 3 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 3
      When I click on Activity 4
      Then I am on the Activity 4 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 5
      Then I am on the Activity 5 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 3
      When I click on Activity 6
      Then I am on the Activity 6 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 7
      Then I am on the Activity 7 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 8
      Then I am on the Activity 8 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 9
      Then I am on the Activity 9 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 10
      Then I am on the Activity 10 page
      When I click on Complete Activity
      When I click on Session 3
      When I click on Activity 11
      Then I am on the Activity 11 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 3
      When I click on Activity 12
      Then I am on the Activity 12 page
      When I click on Complete Activity
      When I click on Session 3
      
   
      ## SESSION 4

      When I click on Session 4
      When I click on Activity 1
      Then I am on the Activity 1 page
      When I click on Complete Activity
      When I click on Session 4
      When I click on Activity 2
      Then I am on the Activity 2 page
      When I click on Complete Activity
      When I click on Session 4
      When I click on Activity 3
      Then I am on the Activity 3 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 4
      Then I am on the Activity 4 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 5
      Then I am on the Activity 5 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 6
      Then I am on the Activity 6 page
      When I click on Complete Activity
      When I click on Session 4
      When I click on Activity 7
      Then I am on the Activity 7 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 8
      Then I am on the Activity 8 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 9
      Then I am on the Activity 9 page
      When I click on Complete Activity
      When I click on Session 4
      When I click on Activity 10
      Then I am on the Activity 10 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 11
      Then I am on the Activity 11 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 12
      Then I am on the Activity 12 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 13
      Then I am on the Activity 13 page
      When I click on Complete Activity
      When I click on Session 4
      When I click on Activity 14
      Then I am on the Activity 14 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 15
      Then I am on the Activity 15 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 16
      Then I am on the Activity 16 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 17
      Then I am on the Activity 17 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      When I click on Activity 18
      Then I am on the Activity 18 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 4
      
   
      ## SESSION 5

      When I click on Session 5
      When I click on Activity 1
      Then I am on the Activity 1 page
      When I click on Complete Activity
      When I click on Session 5
      When I click on Activity 2
      Then I am on the Activity 2 page
      When I click on Complete Activity
      When I click on Session 5
      When I click on Activity 3
      Then I am on the Activity 3 page
      When I click on Complete Activity
      When I click on Session 5
      When I click on Activity 4
      Then I am on the Activity 4 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 5
      Then I am on the Activity 5 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 6
      Then I am on the Activity 6 page
      When I click on Complete Activity
      When I click on Session 5
      When I click on Activity 7
      Then I am on the Activity 7 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 8
      Then I am on the Activity 8 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 9
      Then I am on the Activity 9 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 10
      Then I am on the Activity 10 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 11
      Then I am on the Activity 11 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      When I click on Activity 12
      Then I am on the Activity 12 page
      When I click the "Next" link
      Then there is a game
      When I click on Session 5
      
   

      Finished using selenium
