Feature: Autogenerated Run-Through

Run through the entire intervention. This test is generated from the
content in the database. Hopefully, this will help us keep 
up to date with changing content. To create this, I run a 
pull_from_prod to the test instance, then run a dev server
on port 8001 with the settings_test and do
curl http://localhost:8001/testgen/ > intervention/features/auto_runthrough.feature
Don't edit this feature file directly. Edit templates/intervention/testgen.html instead

    Scenario: Automated Run-Through
      Using selenium
      Given I am logged in as a counselor
      When I access the url "/"
      When I click the "Let's get started!" link
      When I click the "Intervene" link
      When I fill in "test" in the "name" form field
      When I fill in "test" in the "id_number" form field
      When I submit the "login-participant-form" form
      Then I am on the Intervention page


   
      ## SESSION 1

      When I click on Session 1
      When I click on Activity 1
      Then I am on the "Session Objectives" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 2
      Then I am on the "Welcome to Masivukeni!" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 3
      Then I am on the "Today" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 4
      Then I am on the "Working Together" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 5
      Then I am on the "What are ARVs" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 6
      Then I am on the "Getting to Know ARVs" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 7
      Then I am on the "Taking ARVs" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 8
      Then I am on the "ARV Concerns" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 9
      Then I am on the "How Are You?" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 10
      Then I am on the "Mood Screen" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 11
      Then I am on the "Alcohol Screen" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 12
      Then I am on the "Drug Screen" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 13
      Then I am on the "Treatment Support" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 14
      Then I am on the "Disclosure is Important" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 15
      Then I am on the "Choosing a Buddy" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 16
      Then I am on the "Next Steps with Buddy" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 17
      Then I am on the "Reasons to Stay Healthy" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 18
      Then I am on the "End Session" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      
   
      ## SESSION 2

      When I click on Session 2
      When I click on Activity 1
      Then I am on the "Session Objectives" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 2
      Then I am on the "Welcome" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 3
      Then I am on the "Supporting Each Other" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 4
      Then I am on the "Today" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 5
      Then I am on the "What is HIV" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 6
      Then I am on the "How HIV Works" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 7
      Then I am on the "What HIV Does" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 8
      Then I am on the "HIV Symptoms" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 9
      Then I am on the "ARVs and Adherence" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 10
      Then I am on the "How Adherence Works" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 11
      Then I am on the "Your Questions" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 12
      Then I am on the "Reasons to Stay Healthy" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 13
      Then I am on the "End Session" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      
   
      ## SESSION 3

      When I click on Session 3
      When I click on Activity 1
      Then I am on the "Session Objectives" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 2
      Then I am on the "Welcome to Session 3!" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 3
      Then I am on the "Your ARVs" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 4
      Then I am on the "Starting ARVs" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 5
      Then I am on the "Adherence Is Crucial" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 6
      Then I am on the "Adherence Helpers" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 7
      Then I am on the "Adherence Challenges" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 8
      Then I am on the "No Support" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 9
      Then I am on the "Getting to Clinic" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 10
      Then I am on the "Confused" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 11
      Then I am on the "Feeling Good" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 12
      Then I am on the "Forgetting" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 13
      Then I am on the "Overcoming Challenges" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 14
      Then I am on the "Your Treatment Team" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 15
      Then I am on the "Healthy Living" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 16
      Then I am on the "Eat Well" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 17
      Then I am on the "Exercise" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 18
      Then I am on the "Keep Safe" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 19
      Then I am on the "Find Help" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 20
      Then I am on the "Reasons to Stay Healthy" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 21
      Then I am on the "Commitment to Health" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 22
      Then I am on the "End Session" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      
   
      ## SESSION 4

      When I click on Session 4
      When I click on Activity 1
      Then I am on the "Session Objectives" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 2
      Then I am on the "Welcome back" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 3
      Then I am on the "Mood Screening" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 4
      Then I am on the "Alcohol Screening" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 5
      Then I am on the "Drug Screening" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 6
      Then I am on the "Your ARVs" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 7
      Then I am on the "HIV, ARVs, and Health" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 8
      Then I am on the "Adherence Challenges" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 9
      Then I am on the "Overcoming Challenges" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 10
      Then I am on the "Overcoming Challenges" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 11
      Then I am on the "Reasons to Stay Healthy" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 12
      Then I am on the "End Session" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 13
      Then I am on the "OPTION: ARV Concerns" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 14
      Then I am on the "OPTION: Support Tree" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 15
      Then I am on the "OPTION: What is HIV" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 16
      Then I am on the "OPTION: How HIV Works" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 17
      Then I am on the "OPTION: What HIV Does" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 18
      Then I am on the "OPTION: HIV Symptoms" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 19
      Then I am on the "OPTION: Island Activity (no ARVs)" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 20
      Then I am on the "OPTION: Snakes and Soldiers Video" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 21
      Then I am on the "OPTION: Island Activity (on ARVs)" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 22
      Then I am on the "OPTION: Joseph and Hope Video" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 23
      Then I am on the "OPTION: Moving Forward Video" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      
   
      ## SESSION 5

      When I click on Session 5
      When I click on Activity 1
      Then I am on the "Session Objectives" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 2
      Then I am on the "Welcome  Back" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 3
      Then I am on the "Overcoming Challenges" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 4
      Then I am on the "Overcoming Challenges" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 5
      Then I am on the "HIV, ARVs, and Health" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 6
      Then I am on the "End Session" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 7
      Then I am on the "OPTION: ARV Concerns" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 8
      Then I am on the "OPTION: Your Regimen" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 9
      Then I am on the "OPTION: Support Tree" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 10
      Then I am on the "OPTION: What is HIV" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 11
      Then I am on the "OPTION: How HIV Works" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 12
      Then I am on the "OPTION: What HIV Does" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 13
      Then I am on the "OPTION: HIV Symptoms" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      When I click on Activity 14
      Then I am on the "OPTION: Island Activity (no ARVs)" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 15
      Then I am on the "OPTION: Snakes and Soldiers Video" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 16
      Then I am on the "OPTION: Island Activity (on ARVs)" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 17
      Then I am on the "OPTION: Joseph and Hope Video" Activity
      When I click the "Next →" link
      Then there is a game
      
      When I click on the Session Home
      When I click on Activity 18
      Then I am on the "OPTION: Moving Forward Video" Activity
      When I click on Complete Activity
      
      When I click on the Session Home
      
   

      Finished using selenium
